services:
  # A Docker web service
  - type: web
    name: webdis
    env: docker
    plan: standard # optional (defaults to starter)
    dockerCommand: ./webdis-wrapper.sh
    envVars:
      - key: REDIS_HOST
        sync: false

      - key: REDIS_PORT
        sync: false
